services:
  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - auction-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
    networks:
      - auction-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=category_service
    networks:
      - auction-network
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    depends_on:
      - mysql
    networks:
      - auction-network

  category-service:
    build:
      context: ./category-service
      dockerfile: Dockerfile
    depends_on:
      discovery-service:
        condition: service_started
      mysql:
        condition: service_healthy
    networks:
      - auction-network
    environment:
      - SPRING_APPLICATION_NAME=category-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/category_service?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456

networks:
  auction-network:
    driver: bridge

volumes:
  mysql-data: