CREATE DATABASE IF NOT EXISTS user_service;
CREATE DATABASE IF NOT EXISTS category_service;
CREATE DATABASE IF NOT EXISTS auction_service;
CREATE DATABASE IF NOT EXISTS bid_service;
CREATE DATABASE IF NOT EXISTS payment_service