# Application name (register with Eureka)
spring.application.name=user-service
spring.profiles.active=default

# Base URL
app.base-url=http://localhost:8082

# DataSource configuration
spring.datasource.url=jdbc:mysql://mysql:3306/user_db
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

# Limit: Run data.sql only after Hibernate has created/updated the tables
spring.jpa.defer-datasource-initialization=true

# Required: Always execute initialization scripts (schema.sql & data.sql) for all DataSources
spring.sql.init.mode=always

# Server
server.port=8082

# JWT
jwt.secret=JX9f56qS1RrY8GxQ5hzKz9g9Z6CtnUqYtFJLeV1n9bM=
jwt.expiration=86400000

# Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lamck27@gmail.com
spring.mail.password=ckhghglbzjyvvpee
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.from=lamck27@gmail.com

# OTP & Token
otp.expiration.minutes=5
verification.token.expiration.hours=24

# Eureka Client configuration
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Logging
logging.level.root=INFO
logging.level.org.springframework.boot=DEBUG
