# Application name (register with Eureka)
spring.application.name=user-service
spring.profiles.active=default

#  Server configuration for mobile 
server.address=0.0.0.0

# Base URL
app.base-url=http://localhost:8082
# Base Frontend
app.frontend-url=http://localhost:3000

# DataSource configuration
spring.datasource.url=jdbc:mysql://mysql:3306/user_service
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

# Limit: Run data.sql only after Hibernate has created/updated the tables
spring.jpa.defer-datasource-initialization=true

# Required: Always execute initialization scripts (schema.sql & data.sql) for all DataSources
spring.sql.init.mode=always

# Server
server.port=8082

# JWT
jwt.secret=JX9f56qS1RrY8GxQ5hzKz9g9Z6CtnUqYtFJLeV1n9bM=
jwt.expiration=86400000

# Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lamck27@gmail.com
spring.mail.password=ckhghglbzjyvvpee
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.from=lamck27@gmail.com

# OTP & Token
otp.expiration.minutes=5
verification.token.expiration.hours=24

# Eureka Client configuration
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Logging
logging.level.root=INFO
# logging.level.org.springframework.boot=DEBUG
logging.level.org.springframework.boot=INFO

# Cloudinary
cloudinary.cloud-name=dxlxou293
cloudinary.api-key=742396862189774
cloudinary.api-secret=9PQm4K0RZAdPn1-epL0bi1ZiV7Y

# Twilio verify phone number
twilio.account.sid=AC550c176a6ed8c1ccd500f7d1870dd9ce
twilio.auth.token=bf47387f629dc4f00a900058bc51c132
twilio.verify.sid=VA21f0483362e4a0b99e565a6234ee4afa

