# Server port
server.port=8761

# Application name
spring.application.name=discovery-service

# Eureka client: 
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Eureka client: URL for the Eureka server
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/
