# Project name
name: mobile_app

# Project description
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev
publish_to: 'none'

# Application version
version: 1.0.0+1

# Dart SDK constraints
environment:
  sdk: ^3.7.2

# Dependencies required for the application
dependencies:
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.0
  http: ^0.13.6
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cloud_firestore: ^4.17.5
  shared_preferences: ^2.5.3

# Development and testing dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter-specific configurations
flutter:
  uses-material-design: true
  assets:
    - assets/images/